"use client";
import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowRight, ChevronDown, Download, Leaf, MapPin, Menu, Network, ShieldCheck, Sprout, TrendingUp, Users, Wifi, X } from "lucide-react";
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, Radar, RadarChart, PolarAngleAxis, PolarGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { faqs, leaders, stats, ventures } from "./data";

const nav = ["Home", "About", "Investment Model", "Portfolio", "Impact", "Farmers", "Leadership", "Insights", "Contact"];
const href = (n: string) => n === "Home" ? "/" : "/" + n.toLowerCase().replaceAll(" ", "-");
const copy = {
  home: ["Farmer Owned Impact Investment Platform", "Building a Farmer Owned Digital Economy", "Kisan Impact Fund invests in scalable businesses that connect Nepali farmers with technology, markets, financial services, infrastructure, and long-term ownership."],
  about: ["About Kisan Impact Fund", "Investment Built Around Farmer Ownership", "A Nepal-based investment and holding company modernizing agriculture through inclusive ownership, disciplined capital and technology."],
  "investment-model": ["Our Investment Model", "Farmers Are Customers — and Owners", "A proposed ownership model aligning farmers, strategic expertise and patient capital around long-term value creation."],
  portfolio: ["Our Portfolio", "Investing Across the Farmer Economy", "A transparent view of flagship, planned and evaluated opportunities across the agricultural value chain."],
  impact: ["Impact & ESG", "Measuring Value Beyond Financial Returns", "A practical framework for tracking income, ownership, access, inclusion, resilience and governance."],
  farmers: ["For Farmers", "From Service Users to Business Owners", "A proposed pathway for eligible farmers and farmer groups to participate in services, governance and long-term ownership."],
  leadership: ["Leadership & Governance", "Leadership Committed to Inclusive Growth", "A board structure designed to combine accountability, farmer-centered purpose and strategic oversight."],
  insights: ["Insights & Notices", "Ideas for a More Inclusive Farmer Economy", "Perspectives, articles, farmer stories, portfolio news, and governance updates."],
  contact: ["Contact Kisan Impact Fund", "Let’s Build the Farmer Economy Together", "Choose the right enquiry path for investment, partnership, farmer participation, portfolio proposals or media."],
  legal: ["Legal & Disclosures", "Clarity Before Participation", "Important corporate, risk, privacy and accessibility information for every visitor."]
};
function Logo({ variant = "light" }: { variant?: "light" | "dark" }) {
  const src = variant === "dark" ? "/logo-dark.png" : "/logo-light.png";
  return <a className="logo" href="/" aria-label="Kisan Impact Fund home"><img src={src} alt="Kisan Impact Fund" /></a>;
}
function Header() { const [open, setOpen] = useState(false); const [solid, setSolid] = useState(false); useEffect(() => { const f = () => setSolid(scrollY > 20); f(); addEventListener("scroll", f); return () => removeEventListener("scroll", f) }, []); return <><div className="announcement">Investing in Farmers. Empowering Futures. <a href="/legal">Read disclosures</a></div><header className={solid ? "solid" : ""}><Logo variant={solid ? "dark" : "light"} /><nav aria-label="Primary">{nav.map(n => <a key={n} href={href(n)}>{n}</a>)}</nav><div className="actions"><a className="button small" href="/contact">Become a Partner</a><button className="menu" onClick={() => setOpen(true)} aria-label="Open menu"><Menu /></button></div></header><AnimatePresence>{open && <motion.div className="drawer" initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }}><button onClick={() => setOpen(false)} aria-label="Close menu"><X /></button><Logo variant="light" />{nav.map(n => <a key={n} href={href(n)}>{n}</a>)}<a href="/legal">Legal & Disclosures</a></motion.div>}</AnimatePresence></> }
const Icon = ({ i }: { i: number }) => [<Users key="u" />, <Network key="n" />, <Leaf key="l" />, <TrendingUp key="t" />, <ShieldCheck key="s" />, <Wifi key="w" />][i % 6];
function Reveal({ children, className = "" }: { children: React.ReactNode, className?: string }) { const reduce = useReducedMotion(); return <motion.div className={className} initial={reduce ? false : { opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .15 }} transition={{ duration: .55 }}>{children}</motion.div> }
function Hero({ page }: { page: keyof typeof copy }) { const c = copy[page] || copy.home; return <section className={`hero hero-${page}`}><div className="hero-bg" /><div className="field-lines" /><div className="hero-shape shape-a" /><div className="hero-shape shape-b" /><motion.div className="hero-copy" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}><span className="eyebrow">{c[0]}</span><h1>{c[1]}</h1><p>{c[2]}</p><div className="hero-actions"><a className="button" href={page === "home" ? "/investment-model" : "/contact"}>{page === "home" ? "Explore Our Investment Model" : "Start a Conversation"}<ArrowRight /></a><a className="text-link" href="/contact">Partner with us <ArrowRight /></a></div></motion.div>{page === "home" && <motion.aside className="hero-intelligence" initial={{ opacity: 0, x: 40 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: .25 }}><div className="intelligence-head"><span>Impact intelligence</span><i>LIVE MODEL</i></div><div className="pulse-row"><div className="pulse"><span /><Wifi /></div><div><small>Connected opportunity</small><b>1.5M households</b></div></div><div className="mini-curve"><i /><i /><i /><i /><i /><i /><i /></div><div className="intelligence-foot"><span><b>49%</b><small>Farmer ownership target</small></span><span><b>13.6L</b><small>Farmer records</small></span></div></motion.aside>}<div className="trust"><span>Farmer-centered ownership</span><span>Technology-enabled businesses</span><span>Sustainable value creation</span><span>Transparent governance</span></div></section> }

const projectionData = [{ year: "Year 1", ebit: 3.5, households: 30 }, { year: "Year 2", ebit: 20, households: 200 }, { year: "Year 3", ebit: 75, households: 500 }, { year: "Year 4", ebit: 150, households: 800 }, { year: "Year 5", ebit: 220, households: 1500 }];
const radarData = [{ metric: "Income", value: 62 }, { metric: "Ownership", value: 49 }, { metric: "Access", value: 71 }, { metric: "Gender", value: 46 }, { metric: "Climate", value: 58 }, { metric: "Governance", value: 76 }];
function GrowthChart() { return <section className="section chart-section"><div className="chart-copy"><span className="eyebrow">Five-year pathway</span><h2>Scale follows infrastructure, trust and reach.</h2><p>The proposed rollout grows from a Sunsari pilot toward a national subscriber ambition. These represent management strategic projections.</p><div className="chart-kpis"><span><small>Target Year 5 EBIT</small><b>NPR 220 Cr</b></span><span><small>Subscriber ambition</small><b>1.5M</b></span></div></div><div className="chart-shell"><div className="chart-label"><b>Projected EBIT</b><span>NPR crore · performance targets</span></div><ResponsiveContainer width="100%" height={360}><AreaChart data={projectionData} margin={{ top: 20, right: 18, left: -10, bottom: 0 }}><defs><linearGradient id="ebitFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#8fcf3c" stopOpacity={.75} /><stop offset="1" stopColor="#8fcf3c" stopOpacity={.04} /></linearGradient></defs><CartesianGrid stroke="#ffffff14" vertical={false} /><XAxis dataKey="year" stroke="#9fb09f" tickLine={false} axisLine={false} /><YAxis stroke="#9fb09f" tickLine={false} axisLine={false} /><Tooltip contentStyle={{ background: "#102d1f", border: "1px solid #ffffff20", color: "#fff" }} formatter={(v) => [`NPR ${v} Cr`, "Projected EBIT"]} /><Area type="monotone" dataKey="ebit" stroke="#b7f05f" strokeWidth={4} fill="url(#ebitFill)" activeDot={{ r: 7, fill: "#d6a637", stroke: "#fff" }} /></AreaChart></ResponsiveContainer><p className="chart-disclaimer">Source: Kisan Net. Subject to performance and governance oversight.</p></div></section> }
function ImpactCommand() { return <section className="section command"><div className="command-top"><div><span className="eyebrow">Impact command center</span><h2>A fuller view of value.</h2></div><p>Integrated reporting architecture tracking key performance indicators and farmer empowerment metrics.</p></div><div className="command-grid"><div className="radar-panel"><ResponsiveContainer width="100%" height={390}><RadarChart data={radarData} outerRadius="72%"><PolarGrid stroke="#ffffff24" /><PolarAngleAxis dataKey="metric" tick={{ fill: "#dce8dc", fontSize: 12 }} /><Radar dataKey="value" stroke="#b7f05f" fill="#8fcf3c" fillOpacity={.38} strokeWidth={3} /></RadarChart></ResponsiveContainer><span className="panel-caption">Balanced impact scorecard</span></div><div className="metric-stack">{radarData.slice(0, 4).map((d, i) => <div key={d.metric}><span className="metric-no">0{i + 1}</span><div><small>{d.metric}</small><b>{d.value}%</b></div><i style={{ "--w": d.value + "%" } as React.CSSProperties} /></div>)}</div><div className="ownership-panel"><span className="panel-caption">Proposed ownership allocation</span><div className="pie-chart-wrap"><ResponsiveContainer width="100%" height={210}><PieChart><Pie data={[{ n: "Farmers / Impact Fund", v: 49 }, { n: "Strategic Partners", v: 51 }]} dataKey="v" nameKey="n" innerRadius={68} outerRadius={95} paddingAngle={3}>{["#8fcf3c", "#4f8f35"].map(c => <Cell key={c} fill={c} />)}</Pie><Tooltip formatter={(v) => [`${v}%`, "Allocation"]} /></PieChart></ResponsiveContainer><div className="ownership-center"><b>49% Min</b><small>farmer target</small></div></div><div className="ownership-mini"><span><i />Farmers / Impact Fund 49% (Min)</span><span><i style={{ background: "#4f8f35" }} />Strategic Partners 51% (Max)</span></div></div></div></section> }
function EcosystemMap() { const nodes = [{ name: "Kisan Net", status: "Flagship" }, { name: "Food Processing", status: "Planned" }, { name: "Carbon Credit", status: "Planned" }, { name: "Kisan Mart", status: "Active" }, { name: "Kisan Gas", status: "Under Evaluation" }, { name: "Travel Mart", status: "Under Evaluation" }, { name: "Kisan Pay", status: "Flagship" }]; return <section className="section ecosystem"><div className="ecosystem-copy"><span className="eyebrow">Connected portfolio architecture</span><h2>One fund. A network of farmer-serving ventures.</h2><p>Kisan Impact Fund operates as a holding platform linked to multiple business verticals and a shared Digital Farmer platform.</p></div><div className="ecosystem-map"><div className="fund-node"><Logo variant="light" /><small>Holding & investment platform</small></div><div className="connector-line" /><div className="venture-nodes">{nodes.map((n, i) => <motion.div key={n.name} whileHover={{ y: -8 }}><span>0{i + 1}</span><Icon i={i} /><b>{n.name}</b><small>{n.status}</small></motion.div>)}</div><div className="platform-band"><Network /><div><b>Digital Farmer Web / Mobile Platform</b><small>Shared layer for onboarding, services, market access and participation</small></div></div></div></section> }
function StatGrid() { return <section className="section"><div className="section-head"><span className="eyebrow">Strategic ambition</span><h2>Scale with purpose. Measure what matters.</h2><p>Targets are directional and create a clear basis for governance, performance review and public accountability.</p></div><div className="stats">{stats.map((s, i) => <Reveal className="stat" key={s[1]}><Icon i={i} /><strong>{s[0]}</strong><span>{s[1]}</span></Reveal>)}</div><p className="note">Targets and projections are strategic goals for sustainable growth and long-term value creation.</p></section> }
function Ownership() { return <section className="section split"><Reveal><span className="eyebrow">Aligned ownership</span><h2>Customers, owners and strategic expertise at one table.</h2><p>This proposed model is designed to align farmers (holding a minimum 49% through Kisan Impact Fund) and strategic partners (holding up to 51%).</p><div className="legend"><span><i style={{ background: "#8fcf3c" }} />Farmers / Kisan Impact Fund · 49% Min</span><span><i style={{ background: "#4f8f35" }} />Strategic partners · 51% Max</span></div></Reveal><Reveal className="donut-chart-wrap" aria-label="Proposed ownership: Farmers and Kisan Impact Fund 49 percent minimum, strategic partners 51 percent maximum"><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={[{ n: "Farmers / Impact Fund", v: 49 }, { n: "Strategic Partners", v: 51 }]} dataKey="v" nameKey="n" cx="50%" cy="50%" innerRadius={80} outerRadius={120} paddingAngle={4}>{["#8fcf3c", "#4f8f35"].map(c => <Cell key={c} fill={c} />)}</Pie><Tooltip formatter={(v) => [`${v}%`, "Ownership Share"]} /></PieChart></ResponsiveContainer><div className="donut-center-text"><b>49% Min</b><small>farmer target</small></div></Reveal></section> }
function Pillars() { return <section className="section sage"><div className="section-head"><span className="eyebrow">Investment thesis</span><h2>Three ideas connect every investment.</h2></div><div className="three">{[["Inclusive Ownership", "Farmers share in the systems they use and help shape."], ["Digital & Market Access", "Infrastructure connects rural enterprise with services and demand."], ["Sustainable Growth", "Commercial discipline and impact measurement advance together."]].map((p, i) => <Reveal className="card" key={p[0]}><Icon i={i} /><span>0{i + 1}</span><h3>{p[0]}</h3><p>{p[1]}</p><a href={i === 0 ? "/farmers" : i === 1 ? "/portfolio" : "/impact"}>Explore <ArrowRight /></a></Reveal>)}</div></section> }
function KisanNet() { return <section className="section dark"><div className="section-head light"><span className="eyebrow">Flagship initiative</span><h2>Kisan Net: digital infrastructure for the farmer economy.</h2><p>Affordable connectivity becomes a foundation for knowledge, commerce, health, financial inclusion and agri-tech.</p></div><div className="net-grid"><div className="dashboard"><div className="dash-top"><Logo variant="dark" /><span>Farmer platform</span></div><div className="signal"><div><small>Farmer records</small><b>13,61,750</b></div><div><small>Infrastructure</small><b>FTTH + Wireless</b></div></div><div className="bars">{[72, 55, 83, 64, 92, 74, 88].map((n, i) => <i key={i} style={{ height: n + "%" }} />)}</div><p>Connectivity · Market access · Digital literacy · Telehealth · Financial services</p></div><div className="net-copy"><span className="tag">FLAGSHIP</span><h3>One network. Many farmer services.</h3><ul><li>Data center in Kalanki, Kathmandu</li><li>Branch office in Pakali, Sunsari</li><li>Phased expansion — coverage rollout active</li></ul><a className="button" href="/portfolio">Explore Kisan Net <ArrowRight /></a></div></div></section> }
function Portfolio({ full = false }: { full?: boolean }) { const [sector, setSector] = useState("All"); const sectors = ["All", ...Array.from(new Set(ventures.map(v => v.sector)))]; const shown = ventures.filter(v => sector === "All" || v.sector === sector); return <section className="section"><div className="section-head"><span className="eyebrow">Portfolio ecosystem</span><h2>{full ? "A portfolio shaped around the farmer economy." : "Building the connective tissue of rural enterprise."}</h2><p>Every initiative is labeled by status. Kisan Net represents the flagship investment.</p></div>{full && <div className="filters" role="group" aria-label="Filter portfolio">{sectors.map(s => <button className={s === sector ? "active" : ""} onClick={() => setSector(s)} key={s}>{s}</button>)}</div>}<div className="portfolio-grid">{shown.slice(0, full ? 20 : 6).map(v => <motion.article layout className="venture" key={v.name}><div><span className={`tag ${v.status.replaceAll(" ", "-").toLowerCase()}`}>{v.status}</span><small>{v.sector}</small></div><h3>{v.name}</h3><p>{v.problem}</p><dl><dt>Proposed solution</dt><dd>{v.solution}</dd>{full && <><dt>Farmer benefit</dt><dd>{v.benefit}</dd><dt>Geographic focus</dt><dd>{v.focus}</dd></>}</dl><button className="text-link">View details <ArrowRight /></button></motion.article>)}</div>{!full && <a className="text-link centered" href="/portfolio">View the portfolio <ArrowRight /></a>}</section> }
function Leadership({ full = false }: { full?: boolean }) { return <section className="section sage"><div className="section-head"><span className="eyebrow">Leadership</span><h2>Stewardship for inclusive, disciplined growth.</h2><p>Our leadership brings together experienced stewards across agriculture, finance, digital infrastructure, and governance.</p></div><div className="people">{leaders.slice(0, full ? 10 : 4).map((l, i) => <article className="person" key={l[0]}><div className="person-img-wrap"><img src={`/images/leadership/${encodeURIComponent(l[2])}`} alt={`Portrait of ${l[0]}`} loading={i > 3 ? "lazy" : "eager"} /><div className="person-overlay"><span className="person-overlay-tag">{l[1]}</span><span className="person-overlay-action">View Profile <ArrowRight /></span></div></div><div className="person-info"><span>{l[1]}</span><h3>{l[0]}</h3><p>Leading strategy, operations, and community impact initiatives across Kisan Impact Fund.</p></div></article>)}</div>{!full && <a className="text-link centered" href="/leadership">Meet the board <ArrowRight /></a>}</section> }
function FAQ() { const [open, setOpen] = useState(0); return <section className="section narrow"><div className="section-head"><span className="eyebrow">Common questions</span><h2>Clarity before participation.</h2></div><div className="faqs">{faqs.map((f, i) => <div className="faq" key={f[0]}><button aria-expanded={open === i} onClick={() => setOpen(open === i ? -1 : i)}>{f[0]}<ChevronDown /></button>{open === i && <p>{f[1]}</p>}</div>)}</div></section> }
function Form({ farmer = false }: { farmer?: boolean }) {
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    setErrorMsg("");

    const formData = new FormData(e.currentTarget);
    const data: Record<string, any> = { isFarmer: farmer };
    formData.forEach((value, key) => {
      data[key] = value;
    });

    try {
      const res = await fetch("/api/contact", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(data),
      });
      const result = await res.json();
      if (result.success) {
        setDone(true);
      } else {
        setErrorMsg(result.error || "Failed to submit enquiry. Please try again.");
      }
    } catch (err: any) {
      setErrorMsg("Network error. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <form className="form" onSubmit={handleSubmit}>
      {done ? (
        <div className="success">
          <Sprout />
          <h3>Thank you — your enquiry has been submitted successfully.</h3>
          <p>Our team will review your enquiry and get back to you shortly at info@kisanimpactfund.com.</p>
          <button type="button" onClick={() => setDone(false)}>Submit another response</button>
        </div>
      ) : (
        <>
          {errorMsg && (
            <div style={{ color: "#d9534f", marginBottom: "1rem", fontSize: "0.85rem", background: "#fdf2f2", padding: "0.75rem", borderRadius: "4px", border: "1px solid #f5c6cb" }}>
              {errorMsg}
            </div>
          )}
          <div className="form-grid">
            <label>Full name<input required name="name" /></label>
            {!farmer && <label>Organization<input name="org" /></label>}
            <label>{farmer ? "Mobile number" : "Email"}<input required name={farmer ? "mobile" : "email"} type={farmer ? "tel" : "email"} /></label>
            <label>{farmer ? "Province" : "Phone"}<input required={farmer} name={farmer ? "province" : "phone"} /></label>
            {farmer ? (
              <>
                <label>District<input required name="district" /></label>
                <label>Municipality<input required name="municipality" /></label>
                <label>Cooperative or farmer group<input name="cooperative" /></label>
                <label>Main farming activity<input name="activity" /></label>
                <label>Preferred language<select name="language"><option>English</option><option>नेपाली</option></select></label>
              </>
            ) : (
              <>
                <label>Enquiry type<select required name="enquiryType"><option value="">Select</option><option>Strategic Investment</option><option>Institutional Partnership</option><option>Farmer Registration</option><option>Portfolio Proposal</option><option>Media Enquiry</option><option>General Contact</option></select></label>
                <label>Subject<input required name="subject" /></label>
                <label className="wide">Message<textarea required name="message" rows={5} /></label>
              </>
            )}
          </div>
          <label className="consent"><input type="checkbox" required /> I consent to being contacted about this enquiry.</label>
          <button className="button" type="submit" disabled={loading}>
            {loading ? "Sending Enquiry..." : "Send Enquiry"} <ArrowRight />
          </button>
          <p className="note">Your information is transmitted securely and handled with strict confidentiality.</p>
        </>
      )}
    </form>
  );
}
function Timeline() { return <div className="timeline">{["Four-year nationwide farmer awareness campaign", "Digital farmer data collection", "Establishment in 2081 B.S.", "Kisan Net infrastructure development", "Portfolio development", "National expansion", "Future IPO pathway"].map((t, i) => <Reveal className="milestone" key={t}><b>{String(i + 1).padStart(2, "0")}</b><p>{t}</p></Reveal>)}</div> }
function About() { return <><Hero page="about" /><section className="section split"><div><span className="eyebrow">Company overview</span><h2>Capital organized around farmer agency.</h2></div><div><p className="lead">Kisan Impact Fund is an investment and holding company established through the joint capital of strategic partners and farmers.</p><p>Its purpose is to create, incubate, acquire and scale technology-enabled businesses while keeping farmers at the center of ownership and decision-making.</p><div className="facts"><span><small>Established</small><b>2081 B.S.</b></span><span><small>Head office</small><b>Baluwatar, Kathmandu</b></span></div></div></section><Pillars /><section className="section"><div className="section-head"><span className="eyebrow">Mission & vision</span><h2>Every farmer an entrepreneur and stakeholder.</h2></div><div className="two-cards"><article><h3>Mission</h3><p>Empower Nepali farmers through digital transformation, market access, sustainable value chains, financial inclusion and scalable innovation.</p></article><article><h3>Vision</h3><p>Build a Nepal where farmers participate as owners in the digital and agricultural economy and connect to national and global opportunity.</p></article></div><Timeline /></section><section className="section sage"><div className="section-head"><h2>Governance principles</h2></div><div className="value-grid">{["Farmer First", "Shared Ownership", "Transparency", "Innovation", "Sustainability", "Inclusion", "Accountability"].map((v, i) => <div className="value" key={v}><Icon i={i} /><b>{v}</b></div>)}</div><div className="legal-box"><ShieldCheck /><div><h3>Legal and disclosure governance</h3><p>Corporate, regulatory, shareholding, investment and financial governance policies are overseen by executive and board committees.</p></div></div></section></> }
function Investment() { const [amount, setAmount] = useState(100000); return <><Hero page="investment-model" /><Ownership /><section className="section dark"><div className="section-head light"><span className="eyebrow">Investment lifecycle</span><h2>Structured for evidence, scale and accountability.</h2></div><div className="lifecycle">{["Identify", "Structure", "Launch", "Validate", "Scale", "Exit or List"].map((x, i) => <div key={x}><span>{i + 1}</span><b>{x}</b></div>)}</div></section><GrowthChart /><section className="section split"><div><span className="eyebrow">Investment Calculator</span><h2>Explore indicative partner ranges.</h2><p>Individual: NPR 100,000–10,000,000<br />Institutional: NPR 1,000,000–20,000,000</p><input className="range" type="range" min="100000" max="10000000" step="100000" value={amount} onChange={e => setAmount(+e.target.value)} /><strong className="amount">NPR {amount.toLocaleString()}</strong><p className="note">Interactive calculator for individual and institutional partners.</p></div><div className="legal-box"><ShieldCheck /><div><h3>Proposed farmer promoter shares</h3><p>Up to 10,000 promoter shares, with a proposed accumulation rate of 2,000 per year, subject to official verification, eligibility, and regulatory compliance.</p></div></div></section><section className="section sage"><div className="section-head"><h2>Revenue and value streams</h2></div><div className="value-grid">{["Portfolio dividends", "Capital gains from scaling or exits", "Management and advisory fees", "Returns on seed capital", "Reinvestment into new initiatives"].map((v, i) => <div className="value" key={v}><Icon i={i} /><b>{v}</b></div>)}</div><p className="note">Revenue models, returns, ownership structures, and exit timelines are governed by board charters, legal frameworks, and company performance.</p></section><FAQ /></> }
function Impact() { return <><Hero page="impact" /><section className="section"><div className="section-head"><span className="eyebrow">Impact Scorecard</span><h2>A balanced impact scorecard.</h2><p>Measured metrics across economic empowerment, farmer ownership, digital inclusion, and climate resilience.</p></div><div className="impact-grid">{[["Economic empowerment", 62], ["Farmer ownership", 49], ["Digital inclusion", 71], ["Gender inclusion", 46], ["Rural employment", 58], ["Sustainable agriculture", 67], ["Climate resilience", 43], ["Transparent governance", 76]].map((x, i) => <div className="impact-card" key={x[0]}><Icon i={i} /><span>{x[0]}</span><div><i style={{ width: x[1] + "%" }} /></div><b>{x[1]}%</b></div>)}</div></section><section className="section sage split"><div><span className="eyebrow">Methodology</span><h2>From activity to measurable change.</h2><p>Indicators are defined, baselined, and independently reviewed. Key parameters include household income, farmer shareholders, rural internet access, women’s participation, market reach, carbon reduction, jobs and completed training.</p></div><div className="sdgs"><b>SDG alignment</b>{["1 No Poverty", "2 Zero Hunger", "5 Gender Equality", "8 Decent Work", "9 Innovation & Infrastructure", "10 Reduced Inequalities", "12 Responsible Consumption", "13 Climate Action", "17 Partnerships"].map(s => <span key={s}>{s}</span>)}</div></section></> }
function Farmers() { return <><Hero page="farmers" /><section className="section"><div className="section-head"><span className="eyebrow">Participation journey</span><h2>A clear pathway from identification to ownership.</h2></div><div className="journey">{["Farmer identification", "Eligibility verification", "Digital onboarding", "Ownership & service participation"].map((s, i) => <div key={s}><b>0{i + 1}</b><Icon i={i} /><h3>{s}</h3><p>{["Through eligible cooperatives, women’s groups, farmer groups or the Digital Farmers Mission.", "Company and regulatory criteria are checked before participation.", "Consent, identity and service needs are captured through approved systems.", "Eligible farmers access services and participate under formal terms."][i]}</p></div>)}</div></section><section className="section sage split"><div><span className="eyebrow">Eligibility</span><h2>Who may participate?</h2><ul className="checklist"><li>Agricultural cooperative members</li><li>Small-farmer cooperative members</li><li>Other eligible cooperative members</li><li>Women’s group and farmer group members</li><li>Farmers identified through the Digital Farmers Mission</li></ul></div><div><h3>Register interest</h3><Form farmer /></div></section><FAQ /></> }
function Insights() { const cats = ["News", "Press release", "Farmer story", "Portfolio update", "Investment perspective", "ESG publication", "Notice", "Event"]; return <><Hero page="insights" /><section className="section"><div className="feature-article"><span className="tag">FEATURED PERSPECTIVE</span><small>Investment perspective · Published 2026</small><h2>Why shared ownership can strengthen agricultural value chains</h2><p>Exploring how aligned incentives, infrastructure, and transparent governance strengthen agricultural value chains and support rural enterprise.</p><a className="text-link" href="#articles">Read full article <ArrowRight /></a></div><div id="articles" className="article-grid">{cats.map((c, i) => <article key={c}><span>{c}</span><h3>{["Building digital rails for the farmer economy", "Corporate announcement format", "A connected farmer journey", "Kisan Net development update", "Patient capital for rural systems", "How impact measurement will work", "Governance notice format", "Stakeholder dialogue preview"][i]}</h3><p>Key insights on sustainable agriculture, farmer empowerment, and patient capital.</p><small>Published 2026 · 4 min read</small></article>)}</div></section><section className="section dark newsletter"><div><span className="eyebrow">Fund updates</span><h2>Follow the farmer economy.</h2></div><form onSubmit={e => e.preventDefault()}><label>Email address<input type="email" required placeholder="name@example.com" /></label><button className="button">Join newsletter</button></form></section></> }
function Contact() { return <><Hero page="contact" /><section className="section split contact"><div><span className="eyebrow">Head office</span><h2>Baluwatar, Kathmandu, Nepal</h2><p>General enquiry: <em>info@kisanimpactfund.com</em><br />Investment enquiry: <em>invest@kisanimpactfund.com</em><br />Phone & office hours: <em>Mon - Fri, 9:00 AM - 5:00 PM NPT</em></p><div className="map"><iframe src="https://maps.google.com/maps?q=27.729018,85.333013&z=17&output=embed" width="100%" height="420" style={{ border: 0 }} allowFullScreen loading="lazy" referrerPolicy="strict-origin-when-cross-origin" title="Kisan Impact Fund exact location at 27.729018, 85.333013" /><a className="map-link" href="https://maps.google.com/?q=27.729018,85.333013" target="_blank" rel="noreferrer"><MapPin /> Open location in Google Maps <ArrowRight /></a></div></div><div><h3>Choose an enquiry path</h3><Form /></div></section></> }
function Legal() { const docs = [["Privacy Policy", "We respect your privacy. Contact details submitted through our site are used solely to respond to your enquiries in accordance with applicable data protection regulations."], ["Terms of Use", "Website content is for general corporate and informational purposes. Terms and agreements are established through formal documentation."], ["Investment Disclaimer", "Website information is for general informational purposes and does not constitute financial advice or investment solicitation."], ["Risk Disclosure", "Investments carry operational and financial risk. Performance, returns, structures and timelines are governed by market conditions and formal agreements."], ["Cookie Policy", "This website uses essential local storage for user preferences and privacy choices."], ["ESG Policy", "Our ESG and impact measurement framework aligns with SDG standards and transparent reporting boundaries."], ["Governance Documents", "Our governance framework encompasses a robust code of conduct, conflict-of-interest policies, whistleblower protections, and committee charters."], ["Grievance Mechanism", "Stakeholders may reach out via our dedicated grievance channel for transparent review and resolution."], ["Accessibility Statement", "The site is designed for WCAG 2.2 AA compliance, featuring full keyboard navigation, reduced motion support, and clear visual contrast."]]; return <><Hero page="legal" /><section className="section"><div className="legal-box prominent"><ShieldCheck /><div><h2>Investment disclaimer</h2><p>The information presented on this website is for general corporate and informational purposes only. It does not constitute an offer, solicitation, recommendation, or financial advice. Investment participation is subject to legal documentation, eligibility verification, regulatory approval, risk assessment, and formal acceptance by Kisan Impact Fund.</p></div></div><div className="legal-grid">{docs.map(d => <article key={d[0]}><h3>{d[0]}</h3><p>{d[1]}</p></article>)}</div></section></> }
function Home() { return <><Hero page="home" /><StatGrid /><section className="section split editorial-intro"><Reveal><span className="eyebrow">The fund</span><h2>Investment built around farmer ownership.</h2></Reveal><Reveal><p className="lead">Kisan Impact Fund creates, incubates, acquires and scales companies that generate economic value while keeping farmers at the center of ownership and decision-making.</p><a className="text-link" href="/about">Learn about the fund <ArrowRight /></a></Reveal></section><Pillars /><EcosystemMap /><ImpactCommand /><GrowthChart /><KisanNet /><Portfolio /><Leadership /><section className="section cta"><span className="eyebrow">Partner with purpose</span><h2>Invest in systems that help farmers own the future.</h2><div><a className="button" href="/contact">Become a Strategic Partner <ArrowRight /></a><a className="text-link" href="/contact">Contact the Fund <ArrowRight /></a></div></section></> }
function Footer() { return <footer><div><Logo variant="light" /><p>Investing in Farmers.<br />Empowering Futures.</p></div><div><b>Company</b>{nav.slice(1, 6).map(n => <a href={href(n)} key={n}>{n}</a>)}</div><div><b>Resources</b><a href="/insights">Insights</a><a href="/farmers">Farmer resources</a><a href="/investment-model">Investor information</a><a href="/legal">Legal & disclosures</a></div><div><b>Contact</b><span>Baluwatar, Kathmandu</span><span>Nepal</span><a href="/contact">Enquiry routes</a></div><div className="footline"><span>© 2026 Kisan Impact Fund. All rights reserved.</span><span>Designed for sustainable and inclusive growth.</span></div></footer> }
export default function Site({ slug }: { slug?: string[] }) { const page = (slug?.[0] || "home") as keyof typeof copy; const [cookies, setCookies] = useState(false); useEffect(() => { document.documentElement.lang = "en"; localStorage.removeItem("kif-lang"); setCookies(!localStorage.getItem("kif-cookie")) }, []); const view = useMemo(() => ({ home: <Home />, about: <About />, "investment-model": <Investment />, portfolio: <><Hero page="portfolio" /><Portfolio full /><KisanNet /></>, impact: <Impact />, farmers: <Farmers />, leadership: <><Hero page="leadership" /><Leadership full /><section className="section"><div className="section-head"><h2>Governance architecture</h2><p>Comprehensive governance policies ensure transparency, accountability, and ethical management across all initiatives.</p></div><div className="four">{["Board oversight", "Audit & risk", "Impact & ESG", "Ethics & conduct"].map((x, i) => <div key={x}><Icon i={i} /><h3>{x}</h3><p>Structured oversight ensuring long-term value creation and strict regulatory compliance.</p></div>)}</div></section></>, insights: <Insights />, contact: <Contact />, legal: <Legal /> }[page] || <Home />), [page]); return <><a className="skip" href="#main">Skip to content</a><Header /><main id="main">{view}</main><Footer /><a className="backtop" href="#main" aria-label="Back to top">↑</a>{cookies && <div className="cookie"><div><b>Essential preferences only</b><p>This site stores only your consent choice on this device.</p></div><button onClick={() => { localStorage.setItem("kif-cookie", "ok"); setCookies(false) }}>Accept</button></div>}</> }
